- name: Create Longhorn namespace
  kubernetes.core.k8s:
    name: longhorn-system
    kind: Namespace
    state: present

- name: Download Longhorn repos
  ansible.builtin.git:
    repo: "{{ longhorn_repo_name }}"
    dest: "/tmp/longhorn"
    version: "{{ longhorn_version }}"
    update: true # Automatically pull bug-fixes in

- name: Install Longhorn prerequisites
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    namespace: longhorn-system
  with_items:
    - "/tmp/longhorn/deploy/prerequisite/longhorn-iscsi-installation.yaml"
    - "/tmp/longhorn/deploy/prerequisite/longhorn-nfs-installation.yaml"

- name: Install Longhorn helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install Longhorn
  kubernetes.core.helm:
    chart_ref: longhorn/longhorn
    name: longhorn
    release_namespace: longhorn-system
    values_files:
      - "{{ role_path }}/{{ longhorn_config_file }}"
    update_repo_cache: yes
    release_values:
      taintToleration: "nvidia.com/gpu:NoSchedule"
      service:
        ui:
          type: LoadBalancer
      persistence:
        defaultClassReplicaCount: 3
        defaultDataLocality: disabled
