- name: set type of environment
  ansible.builtin.include_tasks: env.yaml
- name: template config file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: ~/ansible-jupyter/roles/deploy_jhub/files/config.yaml
